#!/bin/bash
while IFS=',' read iusername ipasswd 
  do 
    ./imapsync --host1 "mx.mailcow.com" --user1 "$iusername" --password1 "$ipasswd" \
               --host2 "mz.mailcow.com" --user2 "$iusername" --password2 "$ipasswd" \
               --ssl1 --nossl2 --automap --delete2duplicates --skipcrossduplicates
  done < userpasswd.lst
