#!/bin/bash

# set X-API-Key w write permissions
XAPIKEYW=bac72807-f4b9-408f-838d-71d81c59e8d2
# set hostname
XHOSTNAME=mx.mailcow.com

# set IFS
IFS=$','

# Read user and password
while read -r iusername ipasswd; do

# debug only
# printf "\tCreating user: %s and password: %s\n" $iusername $ipasswd

curl --header "Content-Type: application/json" \
  --header "X-API-Key: $XAPIKEYW" \
  --request POST \
  --data '{"attr": {"password":"'"$ipasswd"'","password2":"'"$ipasswd"'"}, "items": "'"$iusername"'"}' \
  https://$XHOSTNAME/api/v1/edit/mailbox

echo

done < userpasswd.lst
