#!/bin/bash

# set X-API-Key w write permissions
XAPIKEY=25EF16-BAA152-6C4A25-C7035B-F1BC94
# set hostname
XHOSTNAME=172.17.61.105

# set IFS
IFS=$','

# Read user and password
while read -r iusername ipasswd; do

# debug only
# printf "\tCreating user: %s and password: %s\n" $iusername $ipasswd

curl --header "Content-Type: application/json" \
  --header "X-API-Key: $XAPIKEY" \
  --request POST \
  --data '{"attr": {"password":"'"$ipasswd"'","password2":"'"$ipasswd"'"}, "items": "'"$iusername"'"}' \
  http://$XHOSTNAME/api/v1/edit/mailbox

done < userpasswd.lst
